databases:
  - name: blog-db
    databaseName: blog_news_db
    user: blog_user
    plan: free

services:
  - type: web
    name: blog-backend
    runtime: python
    plan: free
    region: oregon
    buildCommand: "./build.sh"
    startCommand: "gunicorn blog_project.wsgi --log-file -"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blog-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
      - key: CORS_ALLOWED_ORIGINS
        value: https://blog-frontend-cyzu.onrender.com
      - key: WEB_CONCURRENCY
        value: 4
    rootDir: backend

  - type: web
    name: blog-frontend
    runtime: node
    plan: free
    region: oregon
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    envVars:
      - key: NEXT_PUBLIC_API_BASE_URL
        value: https://blog-backend-u399.onrender.com/api/v1
