databases:
  - name: blog-db
    databaseName: blog_news_db
    user: blog_user

services:
  - type: web
    name: blog-backend
    runtime: python
    region: oregon
    buildCommand: "./build.sh"
    startCommand: "gunicorn blog_project.wsgi --log-file -"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blog-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    rootDir: backend

  - type: web
    name: blog-frontend
    runtime: node
    region: oregon
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    envVars:
      - key: NEXT_PUBLIC_API_BASE_URL
        value: https://YOUR_BACKEND_URL_HERE/api/v1
